### PR TITLE
Patch 5

### PR DESCRIPTION
**Pull request by Tofugrass**

### CODE REVIEW

**Comment by Tofugrass** [comment]
fixed it i think its correct now. i added the verticalmode description

**Comment by Szum123321** [comment]
Sadly this comment is not descriptive enough.
Also Enable → true, Disable → false
I've changed kickSpeed intentionally, because I felt like it was too low after all

**Comment by Tofugrass** [comment]
i forked it before u changed kickspeed, so when i commited it, it registered that i changed it. i just undid that. so now its what yours is. there are also other bugs in the config file that i fixed.

and as an english speaker that description describes exactly what it does is english

**Comment by Szum123321** [comment]
I just feel it can give some more info on what exactly is going to happen, because it's not really vertical mode, it's much more horizontal that way

**Comment by Tofugrass** [comment]
Yes because you swapped it. Now its horizontal mode. Just change the name and its perfect.

**Comment by Tofugrass** [comment]
my fork is always behind your changes so i have no idea what youre changing

**Comment by Tofugrass** [comment]
thats how kickspeed got changed

**Comment by Szum123321** [comment]
No, I think I'll close this pr and do it myself

**Comment by Tofugrass** [comment]
did u see the bugs, i believe there were 2.

**Comment by Szum123321** [comment]
Yes, I saw the 'point' and I believe that it was the only one

**Comment by Tofugrass** [comment]
well since u changed vertical mode to horizontal mode, it needs to be set to disable by default so users experience no change.

**Comment by Szum123321** [comment]
and it is

**Comment by Szum123321** [comment]
https://github.com/Szum123321/elytra_swap/blob/e7eb14327fb1fa2907c2dc57f0e645e5e8d2aca9/src/main/java/net/szum123321/elytra_swap/ConfigHandler.java#L51-L54

**Comment by Tofugrass** [comment]
looks much better, can i get an updated tar for testing

**Comment by Szum123321** [comment]
Sure, but under the original issue

**Pull request closed without merging**
